# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160801_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Teckel', 'verbose_name_plural': 'Teckles'},
        ),
    ]
