# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_item_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comentarios'),
        ),
    ]
