# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 19:03
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models.banner
import main.models.category
import main.models.item


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('image', models.ImageField(max_length=1000, upload_to=main.models.banner.upload_to, verbose_name='image')),
            ],
            options={
                'verbose_name_plural': 'banners',
                'verbose_name': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('header_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to=main.models.category.upload_to, verbose_name='header image')),
                ('thumbnail', models.ImageField(blank=True, max_length=1000, null=True, upload_to=main.models.category.upload_to, verbose_name='miniature image')),
                ('meta_tag', models.CharField(blank=True, max_length=500, null=True, verbose_name='meta tag')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', related_query_name='parent', to='main.Category', verbose_name='parent category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'verbose_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=100, verbose_name='reference_code')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('starred', models.BooleanField(default=False, verbose_name='starred')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='wholesale price')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('times_sold', models.PositiveIntegerField(default=0, verbose_name='times sold')),
                ('shown_times', models.PositiveIntegerField(default=0, verbose_name='shown times')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to=main.models.item.upload_to)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='main.Category', verbose_name='category')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'verbose_name': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slogan', models.CharField(blank=True, max_length=150, null=True, verbose_name='slogan')),
                ('address', models.CharField(blank=True, max_length=75, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='city')),
                ('town_ship', models.CharField(blank=True, max_length=20, null=True, verbose_name='town ship')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='zip code')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='country')),
                ('tax_number', models.CharField(max_length=20, verbose_name='utr')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('terms_use_privacy', models.TextField(blank=True, null=True, verbose_name='terms of use and privacy')),
                ('return_policy', models.TextField(blank=True, null=True, verbose_name='return policy')),
            ],
            options={
                'verbose_name': 'shop information',
            },
        ),
    ]
