# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160801_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='upload_date',
        ),
    ]
